### ISSUE TITLE
Improve responsiveness

### ISSUE THREAD

**Issue by 0ffz** [MineInAbyss/StaminaClimb#17]
The code is pretty old and messy, there's probably tons of dumb decisions being made that cause the system to be less responsive. A rewrite would probably be the easiest way to fix it...

We should also make the system more forgiving for right clicking early or late, and consider some high ping situations.

**Comment by venikman1** [comment]
@0ffz
Can I take this one?

**Comment by 0ffz** [comment]
Sure, though honestly taking up #18 first would probably help with this one. You could just copy paste how we do configs in other places and ask for help if needed.

**Comment by 0ffz** [comment]
Too broad of an issue, we'll get that geary rewrite done and then focus on specific things that should be improved.
